import Database from "better-sqlite3";
import { drizzle, type BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import * as schema from "./schema";

/**
 * Single SQLite connection reused across the process. Next.js reloads modules
 * on HMR in dev, which would otherwise open a new file handle every edit; we
 * stash the instance on globalThis to survive reloads.
 */
type Db = BetterSQLite3Database<typeof schema>;

const globalForDb = globalThis as unknown as {
  __ferrataDb?: Db;
  __ferrataSqlite?: Database.Database;
};

const DB_PATH = process.env.FERRATA_DB_PATH ?? "./ferrata.db";

function create(): Db {
  const sqlite = new Database(DB_PATH);
  sqlite.pragma("journal_mode = WAL");
  sqlite.pragma("foreign_keys = ON");
  sqlite.pragma("busy_timeout = 5000");

  const db = drizzle(sqlite, { schema });

  // Apply migrations at boot so a clean machine needs no extra step. The folder
  // is generated by `pnpm db:generate` and committed. Tolerant of idempotent
  // re-application.
  //
  // Skipped during `next build`, where parallel page-data workers would race on
  // the same file. Since the connection became lazy this should be unreachable,
  // because a build imports and never queries; it stays because the cost is one
  // environment read and the failure it guards against is a corrupted migration
  // sequence on somebody's first install.
  const migrationsFolder = resolve(process.cwd(), "drizzle");
  const isBuild = process.env.NEXT_PHASE === "phase-production-build";
  if (existsSync(migrationsFolder) && !isBuild) {
    try {
      migrate(db, { migrationsFolder });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (!/duplicate column|already exists/i.test(msg)) throw err;
    }
  }

  globalForDb.__ferrataSqlite = sqlite;
  return db;
}

let instance: Db | undefined;

/**
 * The connection, opened the first time somebody actually queries.
 *
 * Deliberately not opened when this module is imported, and that is the whole
 * point of the indirection below. `next build` collects page data by importing
 * every page in parallel workers, and each worker is a separate V8 environment
 * inside one process. better-sqlite3 registers a cleanup hook per environment,
 * so a connection opened merely because some page imported this file is later
 * torn down against an environment that is not the one that registered it. On
 * Windows that is not an exception but an abort: `Assertion failed: (env) !=
 * nullptr`, and a native stack whose only readable frame is a Statement
 * destructor, which is why the build died with nothing at all pointing at the
 * database. Nothing in the app queries at module scope, so deferring is enough:
 * the page-data workers import this and never open a handle.
 */
function connection(): Db {
  instance ??= globalForDb.__ferrataDb ?? create();
  // HMR swaps this module on every edit in dev. Stashing the instance keeps the
  // next copy on the same handle instead of opening another one per edit.
  if (process.env.NODE_ENV !== "production") globalForDb.__ferrataDb = instance;
  return instance;
}

/**
 * Drizzle, in the shape every call site already expects.
 *
 * A proxy rather than a `getDb()` function so that opening late costs nothing
 * at the hundreds of places that import `db` and use it as a value. Methods are
 * bound to the real instance rather than left to receive the proxy as `this`,
 * because Drizzle's classes carry private fields and a private read through a
 * proxy throws.
 */
export const db: Db = new Proxy({} as Db, {
  get(_target, prop) {
    const real = connection();
    const value: unknown = Reflect.get(real, prop);
    return typeof value === "function" ? value.bind(real) : value;
  },
  set(_target, prop, value) {
    return Reflect.set(connection(), prop, value);
  },
  has: (_target, prop) => Reflect.has(connection(), prop),
});

/**
 * Fold the write-ahead log back into the database file.
 *
 * WAL is right for this workload, but it means that on disk the database is
 * `ferrata.db` plus a `-wal` holding everything written since the last
 * checkpoint. Somebody will copy the one file, because it is the obvious thing
 * and because the docs said so, and get a database silently rolled back to that
 * checkpoint: it opens, it restores, and the last hour is missing. That is the
 * worst way for a backup to fail, and documenting it is a weaker fix than
 * removing it.
 *
 * So the worker calls this when it runs out of work. Ferrata writes a few times
 * a minute, not thousands of times a second, so a truncating checkpoint at idle
 * costs nothing measurable and leaves the WAL empty almost always. `pnpm
 * db:backup` remains the correct way; this makes the incorrect way usually
 * harmless.
 */
export function checkpoint(): void {
  // An escape hatch, and it exists because on Windows this operation has been
  // seen to end the process rather than fail. The driver can abort instead of
  // throwing, so the catch below is no protection at all, and an operator
  // whose server dies a second after starting needs a way to rule this out
  // without editing code. Turning it off costs what the comment above
  // describes: the write-ahead log is no longer folded back at idle, so
  // somebody who copies the one database file gets it as of the last
  // checkpoint. `pnpm db:backup` is unaffected and remains correct.
  if (process.env.FERRATA_NO_CHECKPOINT === "1") return;
  try {
    globalForDb.__ferrataSqlite?.pragma("wal_checkpoint(TRUNCATE)");
  } catch {
    // A checkpoint that cannot run right now (a reader holding the file) is not
    // a failure worth interrupting anything for: the next idle tick retries.
  }
}

/**
 * The underlying connection, for the two things Drizzle cannot express: the
 * checkpoint above, and SQLite's backup API. Nothing else should reach for it.
 */
export function sqlite(): Database.Database {
  // Forces the connection: the backup asks for this before anything has
  // necessarily run a query, and "no connection yet" is not an error, it just
  // means nobody has needed one so far.
  connection();
  const handle = globalForDb.__ferrataSqlite;
  if (!handle) throw new Error("no sqlite connection");
  return handle;
}

export { schema };
