import Database from "better-sqlite3";
import { drizzle, type BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import * as schema from "./schema";

/**
 * Single SQLite connection reused across the process. Next.js reloads modules
 * on HMR in dev, which would otherwise open a new file handle every edit; we
 * stash the instance on globalThis to survive reloads.
 */
type Db = BetterSQLite3Database<typeof schema>;

const globalForDb = globalThis as unknown as {
  __ferrataDb?: Db;
  __ferrataSqlite?: Database.Database;
};

const DB_PATH = process.env.FERRATA_DB_PATH ?? "./ferrata.db";

function create(): Db {
  const sqlite = new Database(DB_PATH);
  sqlite.pragma("journal_mode = WAL");
  sqlite.pragma("foreign_keys = ON");
  sqlite.pragma("busy_timeout = 5000");

  const db = drizzle(sqlite, { schema });

  // Apply migrations at boot so `pnpm dev` works on a clean machine with no
  // extra step. The folder is generated by `pnpm db:generate`. Skipped during
  // `next build` (parallel page-data workers would race on the same file), and
  // tolerant of idempotent re-application.
  const migrationsFolder = resolve(process.cwd(), "drizzle");
  const isBuild = process.env.NEXT_PHASE === "phase-production-build";
  if (existsSync(migrationsFolder) && !isBuild) {
    try {
      migrate(db, { migrationsFolder });
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (!/duplicate column|already exists/i.test(msg)) throw err;
    }
  }

  globalForDb.__ferrataSqlite = sqlite;
  return db;
}

export const db: Db = globalForDb.__ferrataDb ?? create();
if (process.env.NODE_ENV !== "production") globalForDb.__ferrataDb = db;

export { schema };
